#!/bin/bash
#
# Setup various types of CMake builds

# Make the script a little more friendly
set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

#######################################
# Settings
#
# Parent directory for all build types
BUILD_DIR="build"
# Build generator to use, probably "Ninja" or "UNIX Makefiles"
BUILD_GENERATOR="Ninja"

# Simple build types (non-instrumented)
# Compilers to test with simple configs. Note these are arrays and need to pair up
SIMPLE_C=( gcc clang )
SIMPLE_CXX=( g++ clang++ )
# Types to iterate all of the simple compiler setups through
SIMPLE_TYPES="Debug Release"

# Sanitizers
CLANG_SANITIZER_C=( clang )
CLANG_SANITIZER_CXX=( clang++ )
CLANG_SANITIZER_NAMES=( asan msan tsan ubsan )
CLANG_SANITIZER_ARGS=( USE_SANITIZER_ADDRESS USE_SANITIZER_MEMORY USE_SANITIZER_THREAD USE_SANITIZER_UNDEFINED )
CLANG_SANITIZER_TYPES="Debug Release"
GCC_SANITIZER_C=( gcc )
GCC_SANITIZER_CXX=( g++ )
GCC_SANITIZER_NAMES=( asan lsan tsan ubsan )
GCC_SANITIZER_ARGS=( USE_SANITIZER_ADDRESS USE_SANITIZER_LEAK USE_SANITIZER_THREAD USE_SANITIZER_UNDEFINED )
GCC_SANITIZER_TYPES="Debug Release"

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

log() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@"
}

#######################################
# Sets up a specific build configuration
# Globals:
#   BUILD_DIR
#   BUILD_GENERATOR
# Arguments:
#   subdirectory to put build in
#   arguments to pass to CMake (except generator)
# Returns:
#   None
#######################################
specific_build() {
  local directory="${BUILD_DIR}/${1}"
  local arguments="${2}"
  if [[ ! -d "${directory}" ]]; then
    log "Creating ${directory} build"
    mkdir -p "${directory}"
    cd "${directory}"
    cmake ${arguments} -G ${BUILD_GENERATOR} "../.."
    cd - > /dev/null
  else
    log "WARNING ${directory} already exists. Skipping configuration..."
  fi
}

# Simple builds
for idx in "${!SIMPLE_C[@]}"; do
  compilers="-D CMAKE_C_COMPILER=${SIMPLE_C[idx]} -D CMAKE_CXX_COMPILER=${SIMPLE_CXX[idx]}"
  for type in ${SIMPLE_TYPES}; do
    dir="${SIMPLE_C[idx]}-${type}"
    # Force dir to lowercase
    dir=${dir,,}
    arguments="${compilers} -DCMAKE_BUILD_TYPE=${type}"
    specific_build "${dir}" "${arguments}"
  done
done

# Sanitizer builds (Clang)
for idx1 in "${!CLANG_SANITIZER_C[@]}"; do
    compilers="-D CMAKE_C_COMPILER=${CLANG_SANITIZER_C[idx1]} -D CMAKE_CXX_COMPILER=${CLANG_SANITIZER_CXX[idx1]}"
    for type in ${CLANG_SANITIZER_TYPES}; do
	for idx2 in "${!CLANG_SANITIZER_NAMES[@]}"; do
	    dir="${CLANG_SANITIZER_C[idx1]}-${type}-${CLANG_SANITIZER_NAMES[idx2]}"
	    # Force dir to lowercase
	    dir=${dir,,}
	    arguments="${compilers} -D${CLANG_SANITIZER_ARGS[idx2]}=True"
	    specific_build "${dir}" "${arguments}"
	done
    done
done

# # Sanitizer builds (gcc)
for idx1 in "${!GCC_SANITIZER_C[@]}"; do
    compilers="-D CMAKE_C_COMPILER=${GCC_SANITIZER_C[idx1]} -D CMAKE_CXX_COMPILER=${GCC_SANITIZER_CXX[idx1]}"
    for type in ${GCC_SANITIZER_TYPES}; do
	for idx2 in "${!GCC_SANITIZER_NAMES[@]}"; do
	    dir="${GCC_SANITIZER_C[idx1]}-${type}-${GCC_SANITIZER_NAMES[idx2]}"
	    # Force dir to lowercase
	    dir=${dir,,}
	    arguments="${compilers} -D${GCC_SANITIZER_ARGS[idx2]}=True"
	    specific_build "${dir}" "${arguments}"
	done
    done
done

